services:
  postgress:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgresspw
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  